dist: xenial
language: python
python:
  - "3.7.2"
services: postgresql
env:
  - DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION  
  - pip install -r requirements_build.txt
script:
  - python manage.py test -k
deploy:
  provider: heroku
  api_key: a0976ff9-b000-4815-816d-fbe06692d9ba
  app: qa