dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py collectstatic
script:
  - coverage run --source='.' manage.py test qa
