dist: xenial
language: python
python:
  - "3.7.2"
services: sqlite3
env:
  - DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION  
  - pip install -r requirements.txt
script:
  - coverage run --source='.' manage.py test qa
