<<<<<<< HEAD
# Generated by Django 2.2 on 2019-06-03 14:35
=======
# Generated by Django 2.2 on 2019-06-03 18:46
>>>>>>> 2b21e97dbfe595904610d8c5b4af3a6821839e35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='usuario default', max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField(default='texto default', max_length=1000)),
                ('tags', models.TextField(null=True)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=1000)),
                ('votos', models.IntegerField(default=0)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='VotosRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Resposta')),
            ],
        ),
        migrations.CreateModel(
            name='VotosPerguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
