# Generated by Django 2.2 on 2019-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_votosperguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votosperguntas',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
