# Generated by Django 2.2 on 2019-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190407_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(default='texto default', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='usuario',
            field=models.CharField(default='usuario default', max_length=100),
        ),
    ]
