# Generated by Django 2.2 on 2019-04-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190407_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=1000)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Pergunta')),
            ],
        ),
    ]
