# Generated by Django 2.2 on 2019-06-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190602_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VotosRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Resposta')),
            ],
        ),
    ]
