# Generated by Django 2.2 on 2019-04-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20190421_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
