# Generated by Django 2.2 on 2019-04-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='campo',
        ),
    ]
