# Generated by Django 2.2 on 2019-04-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20190427_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profissao',
        ),
    ]
