# Generated by Django 2.2 on 2019-04-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20190427_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
