# Generated by Django 2.2 on 2019-04-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_auto_20190427_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
